[project]
name = "secret-santa"
version = "0.1.0"
description = "Secret santa draw"
authors = [
    { name = "Ivan Perdomo", email = "iperdomo2016@gmail.com" }
]
dependencies = ["pyyaml"]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["uv_build>=0.8.16,<0.9.0"]
build-backend = "uv_build"

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
    "pytest-repeat>=0.9.3",
]

[project.scripts]
secret_santa = "secret_santa.__main__:main"
